name: colorist
description: "An interactive Flutter application that brings the power of Gemini API directly into your Flutter app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  colorist_ui: ^0.3.0
  firebase_ai: ^3.8.0
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  json_serializable: ^6.11.2
  custom_lint: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/
