// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU5xtyYvB7uhO0pz5RRlvddcdKwu3Q5gg',
    appId: '1:1067769184078:web:31dbb62ed06a3f738b681f',
    messagingSenderId: '1067769184078',
    projectId: 'colorist-workshop-app',
    authDomain: 'colorist-workshop-app.firebaseapp.com',
    storageBucket: 'colorist-workshop-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVIMtb78PODJi-1qIYt_fJbAMtVFavrCc',
    appId: '1:1067769184078:android:6cb04bc9d3eb458d8b681f',
    messagingSenderId: '1067769184078',
    projectId: 'colorist-workshop-app',
    storageBucket: 'colorist-workshop-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDbs4SRI6-vemodVYkjFk4OHB3UcRu-As',
    appId: '1:1067769184078:ios:ccb276550afad78b8b681f',
    messagingSenderId: '1067769184078',
    projectId: 'colorist-workshop-app',
    storageBucket: 'colorist-workshop-app.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDbs4SRI6-vemodVYkjFk4OHB3UcRu-As',
    appId: '1:1067769184078:ios:ccb276550afad78b8b681f',
    messagingSenderId: '1067769184078',
    projectId: 'colorist-workshop-app',
    storageBucket: 'colorist-workshop-app.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU5xtyYvB7uhO0pz5RRlvddcdKwu3Q5gg',
    appId: '1:1067769184078:web:5af5398ce87725678b681f',
    messagingSenderId: '1067769184078',
    projectId: 'colorist-workshop-app',
    authDomain: 'colorist-workshop-app.firebaseapp.com',
    storageBucket: 'colorist-workshop-app.firebasestorage.app',
  );
}
